### ISSUE TITLE
Test::Class::Moose::Report->num_tests_run causing undef warning

### ISSUE THREAD

**Issue by jplindstrom** [houseabsolute/test-class-moose#83]
If there are no tests run, Test::Class::Moose::Report->num_tests_run returns undef because it's using List::Util::num instead of List::Util::num0.

An undef warning is then emitted at Test/Class/Moose/Role/Executor.pm line 66 where the undef from num_tests_run is interpolated in Test::Class::Moose::Role::Executor->runtests.

**Comment by autarch** [comment]
Thanks for the report! Fixed in v0.88.
