### ISSUE TITLE
Please move check for base class into a separate method

### ISSUE THREAD

**Issue by chuckadams** [houseabsolute/test-class-moose#84]
In version 0.81, the check for the TCM base class was moved into Test::Class::Moose::Role::Executor::runtests.  Specifically I'm referring to this line:

https://metacpan.org/source/DROLSKY/Test-Class-Moose-0.88/lib/Test/Class/Moose/Role/Executor.pm#L45

I have a codebase where modules need to be tested in isolation, so I am using a customized parallel executor that only forks a single child process, and lazily loads each module under test.  This was relatively painless to do with TCM 0.80, but since the change was introduced in 0.81 to make this base class check, I have had to copy-paste the entire runtests method into my executor in order to bypass that check, which really isn't good for maintenance in the long run.  Could I ask for a minor refactor that moves this "pre-flight check" into a separate method that I can override?

**Comment by autarch** [comment]
Sure, that sounds reasonable. Patches welcome.

**Comment by autarch** [comment]
Done in v0.89
