### ISSUE TITLE
TODO test regression starting in .72

### ISSUE THREAD

**Issue by Ovid** [houseabsolute/test-class-moose#86]
Starting in TCM .72, `$builder->todo_start` tests are now failing if an exception is thrown. Prior to .72, those tests would pass even if an exception was thrown. Now they don't. Switching to `TODO {...}` causes them to fail even prior to .72. This is probably a Test2 issue, but I'm unsure. In any event, you may have other consumers of TCM who are impacted.

I've attached a zip file (github apparently doesn't like tarballs). It extracts a minimal test case into a `tcm_error/` directory. `cd` into that directory and run `./show_failure`. That will force install TCM .71 and run the test. Then it will force install .72 and rerun the tests. The TODO test fails on .72 and beyond.

Obviously, you probably want to run this on an isolated Perl install :)

[tcm_error.zip](https://github.com/houseabsolute/test-class-moose/files/1522565/tcm_error.zip)

**Comment by Ovid** [comment]
I might add that I cannot (yet) reproduce this failure using any version of https://github.com/Test-More/test-more/. So it might actually be a TCM error, but again, I'm unsure.

**Comment by autarch** [comment]
I think the old behavior sounds like a bug. An exception in side a subtest should be treated as a failure, whether or not we are currently in "todo scope". The todo system is intended to convert normal test failures - `ok(0, ...)` - into passes with some additional metadata. For example ...

```
ok( 1, 'pass' );
{
    local $TODO = 'not passing yet';
    die 'goodbye, cruel world';
    ok( 0, 'the thing' );
}
ok( 1, 'pass also' );

done_testing();
```

This just dies, as you'd expect. I think the reason this used to pass has to do with how the old `Test::Builder` code handled exceptions along with some interaction with whatever TCM was doing.

Under the latest Test2 code, an exception in a subtest is propagated as I'd expect:

```
ok( 1, 'pass' );
{
    local $TODO = 'not passing yet';
    die 'goodbye, cruel world';
    ok( 0, 'the thing' );
}
ok( 1, 'pass also' );

done_testing();
```

This will throw an exception and abort mid-subtest under both old and new versions of `Test::More`. Again, that's exactly what I'd expect to happen.

**Comment by autarch** [comment]
Oops, I realized my second example wasn't showing a subtest.

```perl
ok( 1, 'pass' );
subtest(
    'sub',
    sub {
        local $TODO = 'not passing yet';
        die 'goodbye, cruel world';
        ok( 0, 'the thing' );
    }
);
ok( 1, 'pass also' );

done_testing();
```

This dies in the subtest and that exception is propagated to the top level as expected.

**Comment by autarch** [comment]
@Ovid - thoughts? I'm inclined to close this.

**Comment by Ovid** [comment]
@autarch You're right; the previous behavior was a bug. Would be happy to see a test or two around this if there's not one there, but otherwise happy to see this closed.

**Comment by autarch** [comment]
I added some tests for the next release.
