### ISSUE TITLE
Please make _run_test_class and _run_test_method public

### ISSUE THREAD

**Issue by Ovid** [houseabsolute/test-class-moose#88]
It's trivial to override the executor in `Test::Class::Moose::Runner` to make a custom subclass, but when subclassing `Test::Class::Moose::Executor::Sequential`, I have to use the private methods `_run_test_class` and `_run_test_method` with my `before` modifiers. 

It would be lovely if those were made public so I didn't feel too guilty about those. If those were public, I could easily publish modules which allow verbose output like the following (without needing to extend functionality with PRs such as #76):

<img width="827" alt="screen shot 2017-12-16 at 11 15 43 am" src="https://user-images.githubusercontent.com/24634/34069500-17853d7a-e253-11e7-8e83-4fbb4dc171d9.png">

**Comment by autarch** [comment]
Seems like a good idea. We should probably also have a public `run_test_instance` too.

**Comment by autarch** [comment]
I also realized that for this to really function properly you need a way to pass roles to be applied to the executor into the runner class. Right now it hard codes the Sequential & Executor class names, so there's no way to tell it to use a subclass. Allowing arbitrary roles to be applied to the executor would make it easier for folks to write plugins.

**Comment by autarch** [comment]
This is done in v0.92.
