### ISSUE TITLE
Could we turn Test::Class::Moose::Role::CLI::_test_lib_dirs() into something settable?

### ISSUE THREAD

**Issue by oalders** [houseabsolute/test-class-moose#95]
This is currently hardcoded to `t/lib`: https://metacpan.org/source/DROLSKY/Test-Class-Moose-0.94/lib/Test/Class/Moose/Role/CLI.pm#L265-267

We've had to override this internally in order to be able to deal with having several different test libs in the same repo.  It would be nice if this were an arg we could set via the CLI.  I'm happy to provide a PR if this is something you'd consider.

**Comment by autarch** [comment]
Yes, making this a CLI option with `t/lib` as the default makes a lot of sense to me.

**Comment by autarch** [comment]
PRs welcome, I forgot to say.

**Comment by oalders** [comment]
Great! I will put something together.

**Comment by oalders** [comment]
Closed via #96
